### ISSUE TITLE
mkdir triggers panic

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#1591] opened 2024-11-12 07:05 UTC
I find `mkdir -p /tmp` triggers a panic on Asterinas sometimes. It is easy to reproduce, and the log shows: 
![image](https://github.com/user-attachments/assets/0db3fd68-48e9-462b-8504-26635db1156c)
![image](https://github.com/user-attachments/assets/8684c984-c742-4960-bd2c-c71ca5af4169)

According to the debug information, our `read_cstring` may have some problems. When I enter `mkdir -p /tmp` the kernel actually reads the path `/` instead of `/tmp`.  
```log
[    79.133] INFO : [pid=4][tid=4][id=83][SYS_MKDIR]
[    79.133] DEBUG: dirfd = -100, path = "/", mode = 511
[    79.134] DEBUG: lookup path: FsPath { inner: Absolute("/") }
```
The expected output should be: 
```log
[    96.147] INFO : [pid=9][tid=9][id=83][SYS_MKDIR]
[    96.147] DEBUG: dirfd = -100, path = "/tmp", mode = 511
[    96.148] DEBUG: lookup path: FsPath { inner: Absolute("/tmp") }
[    96.148] DEBUG: syscall return error: Error { errno: EEXIST, msg: Some("file exists") }
[    96.149] INFO : [pid=9][tid=9][id=1][SYS_WRITE]
[    96.149] DEBUG: fd = 2, user_buf_ptr = 0x7ffffffcd558, user_buf_len = 0x32
mkdir: can't create directory '/tmp': File exists
```

**Comment by lucassong-mh** [comment] 2024-11-13 02:44
It appears two problems are shown. The first is the panic point `assert!(!lookup.ctx.parent)` in `fs_resolver.rs`, which will be broken if we manipulate dir `/` directly, and I will fix this soon for robustness.

The second one is that it seems `read_cstring_from_user("/tmp")` returns `"/"` instead. That's very odd then.

**Comment by lucassong-mh** [comment] 2024-11-13 08:29
> It appears two problems are shown. The first is the panic point `assert!(!lookup.ctx.parent)` in `fs_resolver.rs`, which will be broken if we manipulate dir `/` directly, and I will fix this soon for robustness.
> 
> The second one is that it seems `read_cstring_from_user("/tmp")` returns `"/"` instead. That's very odd then.

**Problem 1** is fixed in https://github.com/asterinas/asterinas/pull/1599.

And **Problem 2** is caused by the different `mkdir()` behaviors of Busybox and GNU tools. GNU just issues `mkdir("/tmp")`, while Busybox issues `mkdir("/")` first. Surprisingly if we invoke `busybox mkdir /` it never goes to the expected syscall "sys_mkdir".

So it's the special logic brought by Busybox, not our `read_cstring_from_user()`...

**Closed** 2024-11-28 03:23 UTC
Labels: C-bug
